# Generated by Django 6.0.6 on 2026-07-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, unique=True, verbose_name='Código interno')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='inventory.category', verbose_name='Categoria')),
            ],
        ),
    ]
