# Generated by Django 6.0.6 on 2026-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='', max_length=200, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código interno'),
        ),
    ]
